server:
  port: 8282

spring:
  application:
    name: userauth

  datasource:
    url: jdbc:postgresql://localhost:5432/learntech
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 600000         # 10 minutes
      connection-timeout: 30000    # 30 seconds
      max-lifetime: 1800000        # 30 minutes
      leak-detection-threshold: 30000  # Detect slow connections
      pool-name: HikariPool-Prod
      auto-commit: false
      register-mbeans: true


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Kolkata

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    eurekaServerConnectTimeoutSeconds: 10
    eurekaServerReadTimeoutSeconds: 10
    eurekaServerTotalConnections: 200
    eurekaServerTotalConnectionsPerHost: 50
    executorThreadPoolSize: 10
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
